stages:
  - validate
  - plan
  - apply
  - install-argocd

variables:
  TF_ROOT: k8s-platform
  AWS_DEFAULT_REGION: us-east-1

before_script:
  - cd $TF_ROOT
  - terraform init

validate:
  stage: validate
  image: 
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  script:
    - cd $TF_ROOT
    - terraform init
    - terraform fmt -check
    - terraform validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - k8s-platform/**/*.tf

plan:
  stage: plan
  image: 
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  script:
    - cd $TF_ROOT
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - $TF_ROOT/tfplan
    expire_in: 1 hour
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - k8s-platform/**/*.tf

apply:
  stage: apply
  image: 
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  script:
    - terraform apply -auto-approve tfplan
    - echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> apply.env
    - echo "ECR_REPO=$(terraform output -raw ecr_repository_url)" >> apply.env
  artifacts:
    reports:
      dotenv: $TF_ROOT/apply.env
  dependencies:
    - plan
  environment:
    name: production
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

install_argocd:
  stage: install-argocd
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  before_script: [] 
  script:
    # 1. DOWNLOAD THE REAL APPLICATION ENGINE BINARY (NOT THE WEBPAGE)
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    
    # 2. Make it executable and place it on your runner system path
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    
    # 3. Step into your workspace and connect to AWS
    - kubectl version --client
    - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
    - kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
    - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml --server-side --force-conflicts
    - kubectl apply -f k8s-platform/argocd-app.yaml --server-side
  needs:
    - job: apply
      artifacts: true
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
