stages:
  - validate
  - plan
  - apply
  - install-argocd
  - build
  - push
  - update-manifest

include:
  - local: 'k8s-platform/.gitlab-ci-infra.yml'

variables:
  TF_ROOT: "k8s-platform"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  AWS_DEFAULT_REGION: "us-east-1"

build_and_push:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - apk add --no-cache aws-cli
    - |
      if [ -z "$ECR_REPO"]; then
        echo "Apply stage was skipped. Querying AWS for ECR repository URL..."
        ECR_REPO=$(aws ecr describe-repositories --repository-names learning-website --query 'repositories[0].repositoryUri' --output text 2>/dev/null || echo "$FALLBACK_ECR_REPO")
      fi
    - echo "Using ECR repository -> $ECR_REPO"
    - docker build -t $ECR_REPO:$IMAGE_TAG .
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
    - docker push $ECR_REPO:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - Dockerfile
        - nginx.conf
        - "**/*.html"

update_manifest:
  stage: update-manifest
  image: alpine:latest
  variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  script:
    - apk add --no-cache git aws-cli
    # Ensure the script can locate the target registry link if apply stage
    - |
      if [ -z "$ECR_REPO" ]; then
        ECR_REPO=$(aws ecr describe-repositories --repository-names learning-website --query 'repositories[0].repositoryUri' --output text 2>/dev/null || echo "$FALLBACK_ECR_REPO")
      fi
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/maneeshh007/terraform-k8s.git repo
    - cd repo
    - |
      sed -i "s|image: .*|image: $ECR_REPO:$IMAGE_TAG|" k8s-platform/manifests/website-deployment.yaml
    - git config user.email "ci@pipeline.local"
    - git config user.name "GitLab CI"
    - git commit -am "Update image to $IMAGE_TAG [skip ci]"
    - git push origin main
  needs:
    - job: apply
      artifacts: true
    - job: build_and_push
      artifacts: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - Dockerfile
        - nginx.conf
        - "**/*.html"
