stages:
  - validate
  - plan
  - apply
  - install-argocd
  - build
  - push
  - update-manifest

include:
  - local: 'k8s-platform/.gitlab-ci-infra.yml'

variables:
  TF_ROOT: "k8s-platform"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  AWS_DEFAULT_REGION: "us-east-1"

build_and_push:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script: []
  script:
    - apk update
    - apk add --no-cache --upgrade expat python3 py3-pip
    - aws --version || pip3 install --no-cache-dir --break-system-packages awscli
    - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    - export ECR_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/learning-website"
    - echo "ECR_REPO=$ECR_REPO" >> build.env
    - docker build -t $ECR_REPO:$IMAGE_TAG .
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO
    - docker push $ECR_REPO:$IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

update_manifest:
  stage: update-manifest
  image: alpine:latest
  before_script: []
  variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  script:
    - apk update
    - apk add --no-cache git python3 py3-pip
    - pip3 install --no-cache-dir --break-system-packages awscli
    - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    - export ECR_REPO="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/learning-website"
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/maneeshh007/terraform-k8s.git repo
    - cd repo
    - |
      sed -i "s|image: .*|image: $ECR_REPO:$IMAGE_TAG|" k8s-platform/manifests/website-deployment.yaml
    - git config user.email "ci@pipeline.local"
    - git config user.name "GitLab CI"
    - git commit -am "Update image to $IMAGE_TAG [skip ci]"
    - git push origin main
  needs:
    - job: build_and_push
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
